# Generated by Django 5.2.13 on 2026-06-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('consumption_type', models.CharField(choices=[('餐饮', '餐饮'), ('文具', '文具'), ('饮品', '饮品'), ('其他', '其他')], max_length=20, verbose_name='消费类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费金额')),
                ('consumption_time', models.DateField(db_index=True, verbose_name='消费时间')),
                ('location', models.CharField(choices=[('一食堂', '一食堂'), ('二食堂', '二食堂'), ('校园超市', '校园超市'), ('奶茶店', '奶茶店')], max_length=50, verbose_name='消费地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
                'db_table': 'consumption',
                'ordering': ['-consumption_time'],
            },
        ),
    ]
